version: "3"
services:
  sonarqube:
    image: sonarqube-arm
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_logs:/opt/sonarqube/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonar.entrypoints=http"
      - "traefik.http.routers.sonar.rule=Host(`sonar.localhost`)"
      - "traefik.docker.network=home"
      - "traefik.http.services.sonar.loadbalancer.server.port=9000"
    networks:
      - home
      - internal
    ports:
      - 9142:9000
  db:
    image: postgres:14.5
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    networks:
      - internal

networks:
  home:
    external: true
  internal: